# frozen_string_literal: true

RSpec.describe Necropsy::AstScanner do
  describe '#scan' do
    subject(:scan) { scan_project(project_root) }

    let(:project_root) { create_project(files: files, config: config) }
    let(:config) { nil }
    let(:nodes_by_id) { scan.nodes.to_h { |node| [node.id, node] } }
    let(:nodes_by_graph_id) { scan.nodes.to_h { |node| [node.graph_id, node] } }
    let(:call_pairs) do
      scan.call_sites.map { |site| [nodes_by_graph_id.fetch(site.caller_id).id, site.message] }
    end

    context 'with Ruby method-definition forms' do
      let(:files) do
        {
          'app/models/scanner_sample.rb' => <<~RUBY
            class ScannerSample
              attr_accessor :name
              delegate :title, to: :profile

              def render
                title
              end

              def self.build
                new
              end

              class << self
                def factory
                end

                alias_method :make, :factory
              end

              define_method(:dynamic_render) do
                render
              end

              alias alias_render render
            end

            ScannerSample.new
          RUBY
        }
      end

      it 'collects methods generated by defs, macros, define_method, and aliases' do
        expect(nodes_by_id.keys).to include(
          'file:app/models/scanner_sample.rb',
          'ScannerSample#name',
          'ScannerSample#name=',
          'ScannerSample#title',
          'ScannerSample#render',
          'ScannerSample.build',
          'ScannerSample.factory',
          'ScannerSample.make',
          'ScannerSample#dynamic_render',
          'ScannerSample#alias_render'
        )
        expect(nodes_by_id.fetch('ScannerSample#title').defined_via).to eq(:delegate)
        expect(nodes_by_id.fetch('ScannerSample.make').defined_via).to eq(:alias_method)
        expect(nodes_by_id.fetch('ScannerSample#alias_render').defined_via).to eq(:alias_method)
      end

      it 'records call sites and instantiated classes produced by the definitions' do
        expect(call_pairs).to include(
          ['ScannerSample.build', 'new'],
          ['ScannerSample#dynamic_render', 'render'],
          ['ScannerSample.make', 'factory'],
          ['ScannerSample#alias_render', 'render']
        )
        expect(scan.instantiated_classes).to include('ScannerSample')
      end
    end

    context 'with hierarchy, callbacks, and metaprogramming' do
      let(:files) do
        {
          'app/controllers/scanner_child.rb' => <<~RUBY
            module ScannerConcern
              def decorated
              end
            end

            class ScannerBase
            end

            class TokenValidator
              def validate_each
              end
            end

            class ContractValidator
              def validate
              end
            end

            class ScannerChild < ScannerBase
              include ScannerConcern
              before_action :authenticate
              validates :token, token: true, presence: true
              validates_with ContractValidator

              def dispatch(name)
                send(name)
              end

              def method_missing(name)
              end

              def authenticate
              end
            end
          RUBY
        }
      end

      let(:class_infos) { scan.class_infos.to_h { |class_info| [class_info.id, class_info] } }

      it 'records class relationships and framework entrypoint hints' do
        child_info = class_infos.fetch('ScannerChild')

        expect(child_info.superclass).to eq('ScannerBase')
        expect(child_info.includes).to eq(['ScannerConcern'])
        expect(child_info.dynamic).to eq(true)
        expect(scan.entrypoint_hints).to include(
          Necropsy::EntryPoint.new(node_id: 'ScannerChild#authenticate', reason: :callback_registered),
          Necropsy::EntryPoint.new(node_id: 'TokenValidator#validate_each', reason: :callback_registered),
          Necropsy::EntryPoint.new(node_id: 'ContractValidator#validate', reason: :callback_registered)
        )
      end

      it 'records uncertainty around unresolved dynamic dispatch' do
        dispatch = nodes_by_id.fetch('ScannerChild#dispatch')
        missing = nodes_by_id.fetch('ScannerChild#method_missing')

        expect(scan.uncertainties.fetch(dispatch.graph_id)).to include(match(/Dynamic dispatch/))
        expect(scan.uncertainties.fetch(missing.graph_id)).to include('ScannerChild defines method_missing')
      end
    end

    context 'with value-object declarations' do
      let(:files) do
        {
          'app/models/value_objects.rb' => <<~RUBY
            StructSample = Struct.new(:name, :age)
            DataSample = Data.define(:title)
          RUBY
        }
      end

      it 'expands Struct and Data definitions into accessor nodes' do
        expect(nodes_by_id.fetch('StructSample#name').defined_via).to eq(:struct_new)
        expect(nodes_by_id.fetch('StructSample#name=').defined_via).to eq(:struct_new)
        expect(nodes_by_id.fetch('DataSample#title').defined_via).to eq(:data_define)
        expect(nodes_by_id).not_to include('DataSample#title=')
      end
    end

    context 'with configured factory methods' do
      let(:config) { { rta: { factory_methods: ['spawn'] } } }
      let(:files) do
        {
          'app/models/factory_built.rb' => <<~RUBY
            class FactoryBuilt
            end

            FactoryBuilt.spawn
          RUBY
        }
      end

      it 'uses factory calls as RTA instantiation evidence' do
        expect(scan.instantiated_classes).to include('FactoryBuilt')
      end
    end

    context 'with self constructors' do
      let(:files) do
        {
          'lib/self_constructors.rb' => <<~RUBY
            class ImplicitFactory
              def self.build
                new
              end
            end

            class ExplicitFactory
              def self.build
                self.new
              end
            end

            ImplicitFactory.build
            ExplicitFactory.build
          RUBY
        }
      end

      it 'records new calls with implicit and explicit self receivers' do
        expect(scan.instantiated_classes).to include('ImplicitFactory', 'ExplicitFactory')
      end
    end

    context 'with qualified constants in a lexical scope' do
      let(:files) do
        {
          'lib/qualified_constant.rb' => <<~RUBY
            module QualifiedNamespace
              module Analyzers
                class Runner
                end
              end

              class Service
                def build
                  Analyzers::Runner.new
                end
              end
            end
          RUBY
        }
      end

      it 'resolves the leading segment through the lexical scope' do
        expect(scan.instantiated_classes).to include('QualifiedNamespace::Analyzers::Runner')
      end
    end

    context 'with constants inherited from a superclass' do
      let(:files) do
        {
          'lib/inherited_constant.rb' => <<~RUBY
            class ConstantParent
              class Service
                def self.call
                end
              end
            end

            class ConstantChild < ConstantParent
              def run
                Service.call
              end
            end
          RUBY
        }
      end

      it 'adds superclass namespaces after lexical candidates' do
        caller_id = nodes_by_id.fetch('ConstantChild#run').graph_id
        site = scan.call_sites.find { |candidate| candidate.caller_id == caller_id }

        expect(site.metadata.fetch('receiver_candidates')).to include('ConstantParent::Service')
      end
    end

    context 'with singleton-scope macros, delegation, and absolute constants' do
      let(:files) do
        {
          'app/models/advanced_macros.rb' => <<~RUBY
            class GlobalTarget
            end

            module Namespace
              class LocalTarget
              end

              class Service
                class << self
                  private
                  attr_reader :secret
                  public
                  attr_reader :status
                  define_method(:build) { status }
                  delegate :name, to: :profile, prefix: true
                end
                private_class_method :build
              end

              ::GlobalTarget.new
            end
          RUBY
        }
      end

      it 'creates singleton methods and records delegate receiver calls' do
        expect(nodes_by_id).to include(
          'Namespace::Service.status',
          'Namespace::Service.build',
          'Namespace::Service.profile_name'
        )
        expect(call_pairs).to include(
          ['Namespace::Service.profile_name', 'profile'],
          ['Namespace::Service.profile_name', 'name']
        )
        expect(scan.instantiated_classes).to include('GlobalTarget')
        expect(scan.instantiated_classes).not_to include('Namespace::GlobalTarget')
        expect(nodes_by_id.fetch('Namespace::Service.secret').visibility).to eq(:private)
        expect(nodes_by_id.fetch('Namespace::Service.build').visibility).to eq(:private)
      end
    end

    context 'with indirect method references and super calls' do
      let(:files) do
        {
          'app/models/indirect_calls.rb' => <<~RUBY
            class Parent
              def render
              end
            end

            class Child < Parent
              def render(...)
                super
              end

              def dispatch(items)
                items.map(&:decorate)
                method(:fallback)
                respond_to?(:available?)
                items.method(:private_fallback)
                items.respond_to?(:private_available?, true)
                items.respond_to?(:public_available?, false)
                try(:optional!)
              end
            end
          RUBY
        }
      end

      it 'records super, symbol-to-proc, and symbol-based references' do
        expect(call_pairs).to include(
          ['Child#render', 'render'],
          ['Child#dispatch', 'decorate'],
          ['Child#dispatch', 'fallback'],
          ['Child#dispatch', 'available?'],
          ['Child#dispatch', 'private_fallback'],
          ['Child#dispatch', 'private_available?'],
          ['Child#dispatch', 'public_available?'],
          ['Child#dispatch', 'optional!']
        )
        caller_id = nodes_by_id.fetch('Child#render').graph_id
        super_site = scan.call_sites.find { |site| site.caller_id == caller_id && site.receiver_kind == :super }
        expect(super_site).not_to be_nil

        references = scan.call_sites.select { |site| site.metadata['symbol_reference'] }
        expect(references.find { |site| site.message == 'private_fallback' }.metadata).to include(
          'original_message' => 'method'
        )
        expect(references.find { |site| site.message == 'private_available?' }.metadata).to include(
          'original_message' => 'respond_to?', 'include_private' => true
        )
        expect(references.find { |site| site.message == 'public_available?' }.metadata).to include(
          'original_message' => 'respond_to?', 'include_private' => false
        )
      end
    end

    context 'with visibility, module functions, eval, and Forwardable declarations' do
      let(:files) do
        {
          'app/models/metaprogrammed.rb' => <<~RUBY
            module Tools
              private
              def hidden
              end

              module_function
              def utility
                hidden
              end

              public
              def visible
              end

              module_function :visible
              extend self
            end

            class Registry
              def_delegator :store, :size, :count
              def_delegators :store, :keys, :values
              define_singleton_method(:lookup) { count }
              class_eval do
                def evaluated
                end
              end

              def revised
              end
              def revised
                :latest
              end
            end
          RUBY
        }
      end

      it 'tracks visibility and all generated definition forms' do
        expect(nodes_by_id.fetch('Tools#hidden').visibility).to eq(:private)
        expect(nodes_by_id.fetch('Tools#utility').visibility).to eq(:private)
        expect(nodes_by_id.fetch('Tools.utility').defined_via).to eq(:module_function)
        expect(nodes_by_id.fetch('Tools#visible').visibility).to eq(:private)
        expect(nodes_by_id).to include(
          'Tools.visible', 'Registry#count', 'Registry#keys', 'Registry#values', 'Registry.lookup', 'Registry#evaluated'
        )
        expect(nodes_by_id.fetch('Registry#revised').line).to eq(30)
        expect(scan.class_infos.find { |info| info.id == 'Tools' }.extends).to eq(['Tools'])
        expect(call_pairs).to include(['Tools.utility', 'hidden'])
      end
    end

    context 'with adjacent include candidate groups and test-only callbacks' do
      let(:files) do
        {
          'app/models/includes.rb' => <<~RUBY,
            module Foo
              module Bar
              end
            end
            module A
              module Bar
              end
              class Host
                include Foo::Bar
                include Bar
              end
            end
          RUBY
          'spec/callback_spec.rb' => <<~RUBY
            class SpecOnlyController
              before_action :prepare
              def prepare
              end
            end
          RUBY
        }
      end

      it 'preserves each include and ignores callback roots declared in tests' do
        host = scan.class_infos.find { |info| info.id == 'A::Host' }

        expect(host.includes).to contain_exactly('Foo::Bar', 'A::Bar')
        expect(scan.entrypoint_hints.map(&:node_id)).not_to include('SpecOnlyController#prepare')
      end
    end

    context 'with Rails generated methods' do
      let(:config) { { frameworks: ['rails'] } }
      let(:files) do
        {
          'app/models/generated.rb' => <<~RUBY
            class GeneratedRecord < ApplicationRecord
              enum :status, draft: 0, published: 1
              store_accessor :settings, :color
              belongs_to :account
            end
          RUBY
        }
      end

      it 'keeps generated method declarations owner-scoped' do
        names = scan.nodes.filter_map do |node|
          node.name if node.owner == 'GeneratedRecord' && node.defined_via == :rails_generated
        end

        expect(names).to include('status', 'status=', 'draft?', 'published?', 'color', 'color=', 'account', 'account=')
      end
    end

    context 'with conditional Rails callbacks' do
      let(:config) { { frameworks: ['rails'] } }
      let(:files) do
        {
          'app/controllers/callbacks_controller.rb' => <<~RUBY
            class CallbacksController
              before_action :always, if: enabled?
              before_action if: :authorized?
              before_action unless: "skip_audit?"
              before_action { audit! }
              before_action :never, if: false
              before_action :not_when, unless: true
              def always; end
              def authorized?; end
              def skip_audit?; end
              def audit!; end
              def never; end
              def not_when; end
            end
          RUBY
        }
      end

      it 'does not root statically disabled callbacks and blocks unknown conditions' do
        ids = scan.entrypoint_hints.map(&:node_id)
        symbols = ids

        expect(symbols).to include(
          'CallbacksController#always', 'CallbacksController#authorized?', 'CallbacksController#skip_audit?'
        )
        expect(symbols).not_to include('CallbacksController#never', 'CallbacksController#not_when')
        expect(scan.semantic_blockers.map(&:kind)).to include(:rails_callback_condition)
        callback_root = scan.entrypoint_hints.find { |entry| entry.evidence&.fetch('type', nil) == 'callback_block' }
        callback_call = scan.call_sites.find { |site| site.message == 'audit!' }
        expect(callback_root.node_id).to eq(callback_call.caller_id)
      end
    end

    context 'with modifier definitions and default arguments' do
      let(:files) do
        {
          'lib/modifier_forms.rb' => <<~RUBY
            module ModifierForms
              private def hidden(client = build_client, fallback: keyword_default)
                hidden_body
              end

              def after_private; end

              private attr_reader :private_reader

              def after_private_reader; end

              module_function def utility
                utility_body
              end

              def after_module_function; end
            end
          RUBY
        }
      end

      it 'applies modifier visibility only to the nested definition and scans its defaults' do
        hidden = nodes_by_id.fetch('ModifierForms#hidden')
        utility = nodes_by_id.fetch('ModifierForms#utility')
        utility_copy = nodes_by_id.fetch('ModifierForms.utility')

        expect(hidden.visibility).to eq(:private)
        expect(nodes_by_id.fetch('ModifierForms#after_private').visibility).to eq(:public)
        expect(nodes_by_id.fetch('ModifierForms#private_reader').visibility).to eq(:private)
        expect(nodes_by_id.fetch('ModifierForms#after_private_reader').visibility).to eq(:public)
        expect(utility.visibility).to eq(:private)
        expect(utility_copy.defined_via).to eq(:module_function)
        expect(nodes_by_id.fetch('ModifierForms#after_module_function').visibility).to eq(:public)
        expect(scan.call_sites.select { |site| site.caller_id == hidden.graph_id }.map(&:message)).to contain_exactly(
          'build_client', 'keyword_default', 'hidden_body'
        )
        expect(scan.call_sites.select { |site| site.caller_id == utility_copy.graph_id }.map(&:message))
          .to contain_exactly('utility_body')
      end
    end

    context 'with singleton classes and executable class contexts' do
      let(:files) do
        {
          'lib/singleton_contexts.rb' => <<~RUBY
            class AttachedTarget
            end

            class LexicalHost
              class << AttachedTarget
                def attached
                  attached_body
                end
              end
            end

            class ExecTarget
              class_exec do
                def generated
                  generated_body
                end
              end
            end

            ExecTarget.instance_exec do
              def singleton_generated
                singleton_body
              end
            end
          RUBY
        }
      end

      it 'attaches definitions to the statically known singleton or class owner' do
        expect(nodes_by_id).to include(
          'AttachedTarget.attached', 'ExecTarget#generated', 'ExecTarget.singleton_generated'
        )
        expect(call_pairs).to include(
          ['AttachedTarget.attached', 'attached_body'],
          ['ExecTarget#generated', 'generated_body'],
          ['ExecTarget.singleton_generated', 'singleton_body']
        )
      end
    end

    context 'with dynamic definition surfaces' do
      let(:files) do
        {
          'lib/dynamic_definitions.rb' => <<~RUBY
            class DynamicDefinitions
              attr_reader computed_name
              define_method(computed_name) { dynamic_body }
            end

            target.class_exec do
              def generated
                eval_body
              end
            end

            def target.singleton_method
              singleton_body
            end
          RUBY
        }
      end

      it 'records blockers and isolates bodies from the file root' do
        kinds = scan.semantic_blockers.map(&:kind)
        synthetic_nodes = scan.nodes.select { |node| node.kind == :block_entry && node.defined_via != :file }
        synthetic_callers = synthetic_nodes.map(&:graph_id)

        expect(kinds).to include(
          :dynamic_generated_methods, :dynamic_definition, :variable_eval, :dynamic_singleton_definition
        )
        expect(scan.call_sites.select { |site| %w[dynamic_body eval_body singleton_body].include?(site.message) })
          .to all(satisfy { |site| synthetic_callers.include?(site.caller_id) })
      end
    end

    context 'with dynamic superclass and pattern-conditional ancestry' do
      let(:files) do
        {
          'lib/dynamic_ancestry.rb' => <<~RUBY
            class DynamicChild < build_base
              case config
              in { mixin: }
                include mixin
              end
            end
          RUBY
        }
      end

      it 'does not substitute Object and records the superclass expression call' do
        info = scan.class_infos.find { |candidate| candidate.id == 'DynamicChild' }
        root = nodes_by_id.fetch('file:lib/dynamic_ancestry.rb')

        expect(info).to have_attributes(superclass: nil, superclass_candidates: [], dynamic: true)
        expect(scan.call_sites).to include(have_attributes(caller_id: root.graph_id, message: 'build_base'))
        expect(scan.semantic_blockers).to include(
          have_attributes(kind: :dynamic_ancestry, scope_kind: :owner, scope_value: 'DynamicChild'),
          have_attributes(kind: :dynamic_ancestry)
        )
      end
    end

    context 'with qualified owner lexical nesting' do
      let(:files) do
        {
          'lib/lexical_nesting.rb' => <<~RUBY
            module Lexical
              class Service; end
              class Nested
                def call
                  Service.run
                end
              end
            end

            class Lexical::Qualified
              def call
                Service.run
              end
            end
          RUBY
        }
      end

      it 'does not infer intermediate lexical scopes from a qualified owner name' do
        nested = nodes_by_id.fetch('Lexical::Nested#call')
        qualified = nodes_by_id.fetch('Lexical::Qualified#call')
        nested_site = scan.call_sites.find { |site| site.caller_id == nested.graph_id && site.message == 'run' }
        qualified_site = scan.call_sites.find { |site| site.caller_id == qualified.graph_id && site.message == 'run' }

        expect(nested_site.metadata.fetch('receiver_candidates')).to include('Lexical::Service')
        expect(qualified_site.metadata.fetch('receiver_candidates')).not_to include('Lexical::Service')
      end
    end

    context 'with method removal' do
      let(:files) do
        {
          'lib/removal.rb' => <<~RUBY
            class Removal
              def obsolete; end
              remove_method :obsolete
              undef_method computed_name
            end
          RUBY
        }
      end

      it 'blocks literal and dynamic activation changes instead of trusting stale definitions' do
        expect(scan.semantic_blockers).to include(
          have_attributes(kind: :remove_method, scope_kind: :message, scope_value: 'obsolete'),
          have_attributes(kind: :dynamic_method_removal, scope_kind: :global)
        )
      end
    end
  end
end
