# frozen_string_literal: true

RSpec.describe Necropsy::AstScanner do
  describe '#scan' do
    subject(:scan) { scan_project(project_root) }

    let(:project_root) { create_project(files: files, config: config) }
    let(:config) { nil }
    let(:nodes_by_id) { scan.nodes.to_h { |node| [node.id, node] } }
    let(:call_pairs) { scan.call_sites.map { |site| [site.caller_id, site.message] } }

    context 'with Ruby method-definition forms' do
      let(:files) do
        {
          'app/models/scanner_sample.rb' => <<~RUBY
            class ScannerSample
              attr_accessor :name
              delegate :title, to: :profile

              def render
                title
              end

              def self.build
                new
              end

              class << self
                def factory
                end

                alias_method :make, :factory
              end

              define_method(:dynamic_render) do
                render
              end

              alias alias_render render
            end

            ScannerSample.new
          RUBY
        }
      end

      it 'collects methods generated by defs, macros, define_method, and aliases' do
        expect(nodes_by_id.keys).to include(
          'file:app/models/scanner_sample.rb',
          'ScannerSample#name',
          'ScannerSample#name=',
          'ScannerSample#title',
          'ScannerSample#render',
          'ScannerSample.build',
          'ScannerSample.factory',
          'ScannerSample.make',
          'ScannerSample#dynamic_render',
          'ScannerSample#alias_render'
        )
        expect(nodes_by_id.fetch('ScannerSample#title').defined_via).to eq(:delegate)
        expect(nodes_by_id.fetch('ScannerSample.make').defined_via).to eq(:alias_method)
        expect(nodes_by_id.fetch('ScannerSample#alias_render').defined_via).to eq(:alias_method)
      end

      it 'records call sites and instantiated classes produced by the definitions' do
        expect(call_pairs).to include(
          ['ScannerSample.build', 'new'],
          ['ScannerSample#dynamic_render', 'render'],
          ['ScannerSample.make', 'factory'],
          ['ScannerSample#alias_render', 'render']
        )
        expect(scan.instantiated_classes).to include('ScannerSample')
      end
    end

    context 'with hierarchy, callbacks, and metaprogramming' do
      let(:files) do
        {
          'app/controllers/scanner_child.rb' => <<~RUBY
            module ScannerConcern
              def decorated
              end
            end

            class ScannerBase
            end

            class ScannerChild < ScannerBase
              include ScannerConcern
              before_action :authenticate

              def dispatch(name)
                send(name)
              end

              def method_missing(name)
              end

              def authenticate
              end
            end
          RUBY
        }
      end

      let(:class_infos) { scan.class_infos.to_h { |class_info| [class_info.id, class_info] } }

      it 'records class relationships and framework entrypoint hints' do
        child_info = class_infos.fetch('ScannerChild')

        expect(child_info.superclass).to eq('ScannerBase')
        expect(child_info.includes).to eq(['ScannerConcern'])
        expect(child_info.dynamic).to eq(true)
        expect(scan.entrypoint_hints).to include(
          Necropsy::EntryPoint.new(node_id: 'ScannerChild#authenticate', reason: :callback_registered)
        )
      end

      it 'records uncertainty around unresolved dynamic dispatch' do
        expect(scan.uncertainties.fetch('ScannerChild#dispatch')).to include(match(/Dynamic dispatch/))
        expect(scan.uncertainties.fetch('ScannerChild#method_missing')).to include('ScannerChild defines method_missing')
      end
    end

    context 'with value-object declarations' do
      let(:files) do
        {
          'app/models/value_objects.rb' => <<~RUBY
            StructSample = Struct.new(:name, :age)
            DataSample = Data.define(:title)
          RUBY
        }
      end

      it 'expands Struct and Data definitions into accessor nodes' do
        expect(nodes_by_id.fetch('StructSample#name').defined_via).to eq(:struct_new)
        expect(nodes_by_id.fetch('StructSample#name=').defined_via).to eq(:struct_new)
        expect(nodes_by_id.fetch('DataSample#title').defined_via).to eq(:data_define)
        expect(nodes_by_id).not_to include('DataSample#title=')
      end
    end

    context 'with configured factory methods' do
      let(:config) { { rta: { factory_methods: ['spawn'] } } }
      let(:files) do
        {
          'app/models/factory_built.rb' => <<~RUBY
            class FactoryBuilt
            end

            FactoryBuilt.spawn
          RUBY
        }
      end

      it 'uses factory calls as RTA instantiation evidence' do
        expect(scan.instantiated_classes).to include('FactoryBuilt')
      end
    end
  end
end
