# frozen_string_literal: true

RSpec.describe Necropsy::ReferenceBarrier do
  it 'blocks candidate definitions referenced by ERB, YAML, GraphQL, and scheduler text' do
    files = {
      'lib/barrier_target.rb' => <<~RUBY,
        class BarrierTarget
          def widget_title; end
          def send_digest; end
          def account_status; end
          def perform_cleanup; end
          def cli_dispatch; end
          def truly_dead; end
        end
      RUBY
      'app/views/widgets/index.html.erb' => '<%= widget_title %>',
      'config/jobs.yml' => "handler: send_digest\n",
      'schema/api.graphql' => "accountStatus: String\n",
      'config/schedule.conf' => "nightly = BarrierTarget#perform_cleanup\n",
      'config/command.conf' => "command = bundle exec job --handler cli_dispatch\n"
    }
    config = { cache: { enabled: false }, paths: { analyze: ['lib/**'], reference: ['**/*'] } }

    with_project(files: files, config: config) do |root|
      report = Necropsy::Runner.new(root: root).analyze
      findings = report.findings.to_h { |finding| [finding.node.name, finding] }

      %w[widget_title send_digest account_status perform_cleanup cli_dispatch].each do |name|
        expect(findings.fetch(name)).to have_attributes(classification: :blocked, confidence: :low)
        expect(findings.fetch(name).blockers).to include(
          have_attributes(kind: :unparsed_external_reference, scope_kind: :definition)
        )
      end
      expect(findings.fetch('truly_dead')).to have_attributes(classification: :unreachable)
      expect(report.diagnostics.fetch('non_ruby_reference_barrier')).to include(
        'scanner' => 'portable_ruby',
        'matched_definitions' => 5,
        'matches' => 5
      )

      explanation = Necropsy::Diagnostics.new(report).explain('BarrierTarget#widget_title')
      blocker = explanation.fetch('blockers').first
      expect(blocker.fetch('metadata')).to include(
        'file' => 'app/views/widgets/index.html.erb',
        'line' => 1,
        'snippet' => '<%= widget_title %>',
        'match_kind' => 'method_name'
      )
      expect(Necropsy::Diagnostics.new(report).render(explanation)).to include(
        'Match: <%= widget_title %>'
      )
    end
  end

  it 'requires strong context for common short method names' do
    files = {
      'lib/common_target.rb' => <<~RUBY,
        class CommonTarget
          def call; end
          def run; end
        end
      RUBY
      'README.txt' => "call this command to run the example.\n",
      'README.md' => "# run\n",
      'config/handler.yml' => "handler: :call\n"
    }
    config = { cache: { enabled: false }, paths: { analyze: ['lib/**'], reference: ['**/*'] } }

    with_project(files: files, config: config) do |root|
      findings = Necropsy::Runner.new(root: root).analyze.findings.to_h do |finding|
        [finding.node.name, finding]
      end

      expect(findings.fetch('call')).to have_attributes(classification: :blocked)
      expect(findings.fetch('call').blockers.map(&:metadata)).to include(
        include('match_kind' => 'symbol_or_string')
      )
      expect(findings.fetch('call').blockers.map(&:metadata)).not_to include(include('file' => 'README.txt'))
      expect(findings.fetch('run')).to have_attributes(classification: :unreachable)
    end
  end

  it 'searches only executable Ruby regions of ERB templates' do
    files = {
      'lib/erb_target.rb' => <<~RUBY,
        class ErbTarget
          def html_display_only; end
          def ruby_reference; end
        end
      RUBY
      'app/views/widgets/show.html.erb' => <<~ERB
        <p>html_display_only</p>
        <%= ruby_reference %>
      ERB
    }
    config = { cache: { enabled: false }, paths: { analyze: ['lib/**'], reference: ['**/*'] } }

    with_project(files: files, config: config) do |root|
      findings = Necropsy::Runner.new(root: root).analyze.findings.to_h { |finding| [finding.node.name, finding] }

      expect(findings.fetch('html_display_only')).to have_attributes(classification: :unreachable)
      expect(findings.fetch('ruby_reference')).to have_attributes(classification: :blocked)
      expect(findings.fetch('ruby_reference').blockers.first.metadata).to include(
        'file' => 'app/views/widgets/show.html.erb', 'line' => 2
      )
    end
  end

  it 'ignores comments and Ruby references but blocks conclusions when generated references are skipped' do
    files = {
      'lib/ignored_target.rb' => <<~RUBY,
        class IgnoredTarget
          def comment_only; end
          def erb_comment_only; end
          def erb_multiline_comment_only; end
          def generated_only; end
          def ruby_literal_only; end
        end
      RUBY
      'config/comment.yml' => "# comment_only\nkey: value # comment_only\n",
      'app/views/comment.erb' => "<% # erb_comment_only %>\n<%\n# erb_multiline_comment_only\n%>\n",
      'config/generated/api.yml' => "# This file is automatically generated. DO NOT EDIT.\ngenerated_only\n",
      'config/handwritten.yml' => "description: generated file settings\nhandler: generated_only\n",
      'scripts/reference.rb' => "REFERENCE = 'ruby_literal_only'\n"
    }
    config = { cache: { enabled: false }, paths: { analyze: ['lib/**'], reference: ['**/*'] } }

    with_project(files: files, config: config) do |root|
      report = Necropsy::Runner.new(root: root).analyze
      findings = report.findings.select { |finding| finding.node.owner == 'IgnoredTarget' }

      expect(findings.map(&:classification)).to all(eq(:blocked))
      expect(report.analysis_health).to have_attributes(status: :degraded)
      expect(report.analysis_health.reasons).to include(include('code' => 'reference_scan_incomplete'))
      expect(report.diagnostics.dig('non_ruby_reference_barrier', 'skipped_counts')).to include(
        'generated' => 1
      )
    end
  end

  it 'streams large text files while bounding binary processing' do
    huge = "huge_marker\n#{'x' * (described_class::MAX_FILE_BYTES + 1)}"
    files = {
      'lib/limit_target.rb' => <<~RUBY,
        class LimitTarget
          def binary_marker; end
          def huge_marker; end
        end
      RUBY
      'data/payload.dat' => "binary_marker\0payload",
      'data/huge.txt' => huge
    }
    config = { cache: { enabled: false }, paths: { analyze: ['lib/**'], reference: ['**/*'] } }

    with_project(files: files, config: config) do |root|
      report = Necropsy::Runner.new(root: root).analyze
      findings = report.findings.select { |finding| finding.node.owner == 'LimitTarget' }

      expect(findings.find { |finding| finding.node.name == 'binary_marker' }).to have_attributes(
        classification: :unreachable
      )
      expect(findings.find { |finding| finding.node.name == 'huge_marker' }).to have_attributes(
        classification: :blocked
      )
      expect(report.analysis_health).to have_attributes(status: :complete)
      expect(report.diagnostics.dig('non_ruby_reference_barrier', 'skipped_counts')).to include(
        'binary' => 1
      )
      expect(report.diagnostics.dig('non_ruby_reference_barrier', 'skipped_samples')).to include(
        { 'file' => 'data/payload.dat', 'reason' => 'binary' }
      )
      expect(report.diagnostics.dig('non_ruby_reference_barrier', 'files_streamed')).to eq(1)
      expect(findings.find { |finding| finding.node.name == 'huge_marker' }.blockers).to include(
        have_attributes(kind: :unparsed_external_reference)
      )
    end
  end

  it 'fails closed when the aggregate reference scan byte budget is exhausted' do
    stub_const('Necropsy::ReferenceBarrier::MAX_TOTAL_SCAN_BYTES', 8)
    files = {
      'lib/budget_target.rb' => 'class BudgetTarget; def hidden_reference; end; end',
      'config/reference.txt' => "hidden_reference\n"
    }
    config = { cache: { enabled: false }, paths: { analyze: ['lib/**'], reference: ['**/*'] } }

    with_project(files: files, config: config) do |root|
      report = Necropsy::Runner.new(root: root).analyze
      finding = report.findings.find { |candidate| candidate.node.name == 'hidden_reference' }

      expect(finding).to have_attributes(classification: :blocked)
      expect(report.analysis_health).to have_attributes(status: :degraded)
      expect(report.analysis_health.reasons).to include(include('code' => 'reference_scan_incomplete'))
      expect(report.diagnostics.dig('non_ruby_reference_barrier', 'skipped_counts')).to include('scan_budget' => 1)
    end
  end

  it 'bounds stored matches per physical definition' do
    references = 8.times.map { |index| "item#{index}: bounded_reference" }.join("\n")
    files = {
      'lib/bounded_target.rb' => 'class BoundedTarget; def bounded_reference; end; end',
      'config/references.yml' => references
    }
    config = { cache: { enabled: false }, paths: { analyze: ['lib/**'], reference: ['**/*'] } }

    with_project(files: files, config: config) do |root|
      report = Necropsy::Runner.new(root: root).analyze
      finding = report.findings.find { |candidate| candidate.node.name == 'bounded_reference' }

      expect(finding.blockers.length).to eq(described_class::MAX_MATCHES_PER_DEFINITION)
      expect(report.diagnostics.dig('non_ruby_reference_barrier', 'truncated_matches')).to eq(3)
      human = Necropsy::Reporter.new(report).render(min_confidence: :low)
      expect(human).to include('match item0: bounded_reference')
    end
  end

  it 'keeps tool metadata and test-only text references out of runtime blockers' do
    files = {
      'lib/domain_target.rb' => <<~RUBY,
        class DomainTarget
          def labeled_dead; end
          def fixture_only; end
        end
      RUBY
      'gold.yml' => <<~YAML,
        dead_methods:
          - id: DomainTarget#labeled_dead
            classification: unreachable
      YAML
      'spec/fixtures/template.erb' => '<%= fixture_only %>'
    }
    config = {
      cache: { enabled: false },
      ci: { baseline: 'gold.yml' },
      paths: { analyze: ['lib/**'], reference: ['**/*'] }
    }

    with_project(files: files, config: config) do |root|
      report = Necropsy::Runner.new(root: root).analyze
      findings = report.findings.to_h { |finding| [finding.node.name, finding] }

      expect(findings.fetch('labeled_dead')).to have_attributes(classification: :unreachable)
      expect(findings.fetch('fixture_only')).to have_attributes(classification: :unreachable)
      expect(report.graph.blockers).to include(
        have_attributes(kind: :unparsed_external_reference, caller_domain: :test)
      )
      expect(report.diagnostics.dig('non_ruby_reference_barrier', 'skipped_counts')).to include(
        'tool_metadata' => 2
      )
    end
  end

  it 'excludes only explicitly supplied benchmark metadata paths' do
    files = {
      'lib/benchmark_target.rb' => 'class BenchmarkTarget; def measured_candidate; end; end',
      'bench/reviewed_labels.yml' => "dead_methods:\n  - BenchmarkTarget#measured_candidate\n"
    }
    config = { cache: { enabled: false }, paths: { analyze: ['lib/**'], reference: ['**/*'] } }

    with_project(files: files, config: config) do |root|
      ordinary = Necropsy::Runner.new(root: root).analyze
      ignored = Necropsy::Runner.new(
        root: root,
        ignored_reference_paths: ['bench/reviewed_labels.yml']
      ).analyze

      ordinary_finding = ordinary.findings.find { |finding| finding.node.name == 'measured_candidate' }
      ignored_finding = ignored.findings.find { |finding| finding.node.name == 'measured_candidate' }
      expect(ordinary_finding).to have_attributes(classification: :blocked)
      expect(ignored_finding).to have_attributes(classification: :unreachable)
      expect(ignored.diagnostics.dig('non_ruby_reference_barrier', 'skipped_counts')).to include(
        'tool_metadata' => 2
      )
    end
  end

  it 'recognizes explicit string references to operator methods' do
    files = {
      'lib/operator_target.rb' => 'class OperatorTarget; def <=>(other) = 0; end',
      'config/comparator.yml' => "method: \"<=>\"\n"
    }
    config = { cache: { enabled: false }, paths: { analyze: ['lib/**'], reference: ['**/*'] } }

    with_project(files: files, config: config) do |root|
      finding = Necropsy::Runner.new(root: root).analyze.findings.find do |candidate|
        candidate.node.name == '<=>'
      end

      expect(finding).to have_attributes(classification: :blocked)
      expect(finding.blockers.first.metadata).to include(
        'file' => 'config/comparator.yml',
        'match_kind' => 'symbol_or_string',
        'matched_text' => '<=>'
      )
    end
  end

  it 'recognizes bare Unicode and operator method names' do
    files = {
      'lib/non_ascii_target.rb' => <<~RUBY,
        class NonAsciiTarget
          def 取得; end
          def []; end
        end
      RUBY
      'app/views/value.erb' => '<%= 取得 %>',
      'config/operator.yml' => "operator [] enabled\n"
    }
    config = { cache: { enabled: false }, paths: { analyze: ['lib/**'], reference: ['**/*'] } }

    with_project(files: files, config: config) do |root|
      findings = Necropsy::Runner.new(root: root).analyze.findings.to_h do |finding|
        [finding.node.name, finding]
      end

      expect(findings.fetch('取得')).to have_attributes(classification: :blocked)
      expect(findings.fetch('取得').blockers.first.metadata).to include(
        'file' => 'app/views/value.erb', 'match_kind' => 'method_name'
      )
      expect(findings.fetch('[]')).to have_attributes(classification: :blocked)
      expect(findings.fetch('[]').blockers.first.metadata).to include(
        'file' => 'config/operator.yml', 'match_kind' => 'method_name'
      )
    end
  end

  it 'indexes a large set of non-token candidates before scanning text lines' do
    definitions = 200.times.map { |index| "def 操作_#{index}; end" }.join("\n")
    unrelated_lines = "ordinary text\n" * 2_000
    files = {
      'lib/indexed_target.rb' => "class IndexedTarget\n#{definitions}\nend\n",
      'config/indexed.txt' => "#{unrelated_lines}handler = 操作_137\n"
    }
    config = { cache: { enabled: false }, paths: { analyze: ['lib/**'], reference: ['**/*'] } }

    with_project(files: files, config: config) do |root|
      findings = Necropsy::Runner.new(root: root).analyze.findings.to_h do |finding|
        [finding.node.name, finding]
      end

      expect(findings.fetch('操作_137')).to have_attributes(classification: :blocked)
      expect(findings.fetch('操作_0')).to have_attributes(classification: :unreachable)
    end
  end

  it 'uses qualified owners to narrow same-name definitions' do
    files = {
      'lib/qualified_targets.rb' => <<~RUBY,
        class QualifiedFoo
          def qualified_only; end
          def also_bare; end
        end
        class QualifiedBar
          def qualified_only; end
          def also_bare; end
        end
      RUBY
      'config/qualified.conf' => "target = QualifiedFoo#qualified_only\n",
      'config/mixed.conf' => "target = QualifiedFoo#also_bare fallback also_bare\n"
    }
    config = { cache: { enabled: false }, paths: { analyze: ['lib/**'], reference: ['**/*'] } }

    with_project(files: files, config: config) do |root|
      findings = Necropsy::Runner.new(root: root).analyze.findings.to_h do |finding|
        [finding.node.symbol_id, finding]
      end

      expect(findings.fetch('QualifiedFoo#qualified_only')).to have_attributes(classification: :blocked)
      expect(findings.fetch('QualifiedBar#qualified_only')).to have_attributes(classification: :unreachable)
      expect(findings.fetch('QualifiedFoo#also_bare')).to have_attributes(classification: :blocked)
      expect(findings.fetch('QualifiedBar#also_bare')).to have_attributes(classification: :blocked)
    end
  end
end
