# frozen_string_literal: true

RSpec.describe Necropsy::Guardrail::Quarantine do
  it 'suggests quarantine annotations for findings at the requested confidence' do
    with_project(files: { 'app/sample.rb' => "class Sample\n  def low; end\n\n  def high; end\nend\n" }) do |root|
      low = finding(id: 'Sample#low', confidence: :low, file: 'app/sample.rb', line: 2)
      high = finding(id: 'Sample#high', confidence: :high, file: 'app/sample.rb', line: 4)
      report = report_with_findings([low, high], root: root)

      suggestions = described_class.new(report: report, root: root).suggestions(min_confidence: :high)

      expect(suggestions.map { |suggestion| suggestion[:finding] }).to eq([high])
      expect(suggestions.first[:annotation]).to match(
        /\A# necropsy:quarantine since=\d{4}-\d{2}-\d{2} fingerprint=[0-9a-f]{64}\z/
      )
      expect(suggestions.first[:source_sha256]).to match(/\A[0-9a-f]{64}\z/)
      expect(suggestions.first[:path]).to eq(File.join(root, 'app/sample.rb'))
    end
  end

  it 'writes annotations above target methods without duplicating existing annotations' do
    source = <<~RUBY
      class Sample
        def first
        end

        # necropsy:quarantine since=2000-01-01
        def second
        end
      end
    RUBY

    with_project(files: { 'app/sample.rb' => source }) do |root|
      first = finding(id: 'Sample#first', confidence: :high, file: 'app/sample.rb', line: 2)
      second = finding(id: 'Sample#second', confidence: :high, file: 'app/sample.rb', line: 6)
      report = report_with_findings([first, second], root: root)

      described_class.new(report: report, root: root).write(min_confidence: :high)

      lines = File.readlines(File.join(root, 'app/sample.rb'), chomp: true)
      expect(lines[1]).to match(/  # necropsy:quarantine since=.* fingerprint=[0-9a-f]{64}/)
      expect(lines[5]).to match(/since=2000-01-01 fingerprint=[0-9a-f]{64}/)
      expect(lines.grep(/necropsy:quarantine/).length).to eq(2)
    end
  end

  it 'does not inspect the final line as the previous line for a method on line one' do
    source = "def first\nend\n# necropsy:quarantine since=2000-01-01\n"

    with_project(files: { 'first.rb' => source }) do |root|
      target = finding(id: 'Object#first', confidence: :high, file: 'first.rb', line: 1)
      report = report_with_findings([target], root: root)

      described_class.new(report: report, root: root).write(min_confidence: :high)

      expect(File.readlines(File.join(root, 'first.rb')).first).to match(/necropsy:quarantine/)
    end
  end

  it 'preserves CRLF line endings when writing annotations' do
    source = "class WindowsSample\r\n  def dead\r\n  end\r\nend\r\n"

    with_project(files: { 'windows_sample.rb' => source }) do |root|
      target = finding(id: 'WindowsSample#dead', confidence: :high, file: 'windows_sample.rb', line: 2)
      report = report_with_findings([target], root: root)

      expect(File).to receive(:rename).and_call_original
      described_class.new(report: report, root: root).write(min_confidence: :high)

      rewritten = File.binread(File.join(root, 'windows_sample.rb'))
      expect(rewritten.scan("\r\n").length).to eq(rewritten.lines.length)
      expect(rewritten.gsub("\r\n", '')).not_to include("\n")
    end
  end

  it 'groups physical definitions generated by the same macro line into one annotation' do
    source = "class MacroSample\n  define_methods :first, :second\nend\n"

    with_project(files: { 'app/macro_sample.rb' => source }) do |root|
      first = finding(id: 'MacroSample#first', confidence: :high, file: 'app/macro_sample.rb', line: 2)
      second = finding(id: 'MacroSample#second', confidence: :high, file: 'app/macro_sample.rb', line: 2)
      report = report_with_findings([first, second], root: root)

      described_class.new(report: report, root: root).write(min_confidence: :high)

      annotations = File.readlines(File.join(root, 'app/macro_sample.rb')).grep(/necropsy:quarantine/)
      expect(annotations.length).to eq(1)
      expect(annotations.first).to match(/fingerprints=[0-9a-f]{64},[0-9a-f]{64}/)
    end
  end

  it 'refuses to overwrite a source that changed after suggestions were built' do
    source = "def target\nend\n"

    with_project(files: { 'target.rb' => source }) do |root|
      target = finding(id: 'Object#target', confidence: :high, file: 'target.rb', line: 1)
      quarantine = described_class.new(report: report_with_findings([target], root: root), root: root)
      suggestions = quarantine.suggestions(min_confidence: :high)
      changed = "def target\n  :changed\nend\n"
      File.write(File.join(root, 'target.rb'), changed)
      allow(quarantine).to receive(:suggestions).and_return(suggestions)

      expect { quarantine.write(min_confidence: :high) }.to raise_error(Necropsy::Error, /changed after analysis/)
      expect(File.read(File.join(root, 'target.rb'))).to eq(changed)
    end
  end

  it 'rejects source paths that escape through a symlink' do
    Dir.mktmpdir do |outside|
      outside_file = File.join(outside, 'outside.rb')
      File.write(outside_file, "def escaped; end\n")
      with_project(files: {}) do |root|
        File.symlink(outside_file, File.join(root, 'linked.rb'))
        target = finding(id: 'Object#escaped', confidence: :high, file: 'linked.rb', line: 1)
        quarantine = described_class.new(report: report_with_findings([target], root: root), root: root)

        expect { quarantine.suggestions }.to raise_error(Necropsy::Error, /outside the project/)
      end
    end
  end
end
