# frozen_string_literal: true

require 'date'

module Necropsy
  module Confidence
    class Scorer
      def initialize(graph:, reachability:, project:)
        @graph = graph
        @reachability = reachability
        @project = project
      end

      def findings
        graph.method_nodes.filter_map do |node|
          next if node.test

          classification = classification_for(node)
          next unless classification

          score, level, reasons = score_for(node, classification)
          Finding.new(
            node: node,
            classification: classification,
            confidence: level,
            score: score,
            reasons: reasons,
            evidences: graph.incoming_edges(node.id).flat_map(&:evidences) + graph.alive_evidences(node.id)
          )
        end
      end

      private

      attr_reader :graph, :reachability, :project

      def classification_for(node)
        if reachability.runtime_alive.include?(node.id)
          return :unused if graph.dynamic_enabled? && !graph.dynamic_alive?(node.id)

          nil
        elsif reachability.test_alive.include?(node.id)
          :test_only_reachable
        else
          :unreachable
        end
      end

      def score_for(node, classification)
        reasons = []
        score = base_score(classification)

        if graph.uncertainties(node.id).any?
          score -= 0.35
          reasons << 'Lowered because this node is near unresolved metaprogramming.'
        end

        if graph.class_info(node.owner)&.dynamic
          score -= 0.25
          reasons << 'Lowered because the owner class defines dynamic dispatch.'
        end

        if generated_accessor?(node)
          score -= 0.2
          reasons << 'Lowered because this node is generated by a Ruby accessor DSL.'
        end

        static_count = graph.profiles.count { |profile| profile.kind == :static }
        if static_count > 1
          score += [static_count - 1, 3].min * 0.04
          reasons << "Raised because #{static_count} static analyzers participated."
        end

        evidence_analyzers = graph.incoming_edges(node.id).flat_map(&:evidences).map(&:analyzer).uniq
        if evidence_analyzers.length > 1
          score += 0.08
          reasons << 'Raised because multiple analyzers agree on incoming reachability evidence.'
        end

        if classification == :unreachable && graph.dynamic_enabled? && !graph.dynamic_alive?(node.id)
          score += 0.25
          reasons << 'Static unreachable and absent from dynamic observations.'
        end

        if classification == :unreachable && quarantine_expired?(node)
          score = [score, 0.95].max
          reasons << 'Raised because quarantine annotation has expired without alive evidence.'
        end

        if classification == :unused
          days = observation_days
          if days && days < project.config.min_observation_days
            score -= 0.3
            reasons << "Observation window is #{days} days, below the configured minimum."
          else
            reasons << 'Reachable statically but never observed dynamically.'
          end
        end

        score = [[score, 0.0].max, 1.0].min
        [score, level_for(score), reasons]
      end

      def base_score(classification)
        case classification
        when :unreachable
          graph.profiles.any? { |profile| profile.name == :rta } ? 0.78 : 0.62
        when :test_only_reachable
          0.55
        when :unused
          0.58
        else
          0.25
        end
      end

      def generated_accessor?(node)
        %i[attr_reader attr_writer attr_accessor struct_new data_define].include?(node.defined_via)
      end

      def level_for(score)
        return :certain if score >= 0.9
        return :high if score >= 0.7
        return :medium if score >= 0.45

        :low
      end

      def observation_days
        graph.observation.values.filter_map do |value|
          next unless value.is_a?(Hash)

          value['days'] || value[:days] || value['observation_days'] || value[:observation_days]
        end.map(&:to_i).max
      end

      def quarantine_expired?(node)
        since = quarantine_since(node)
        return false unless since

        since <= Date.today - project.config.quarantine_days
      end

      def quarantine_since(node)
        path = File.join(project.root, node.file)
        return nil unless File.exist?(path)

        window = File.readlines(path, chomp: true)[[node.line - 4, 0].max, 4] || []
        annotation = window.find { |line| line.include?('necropsy:quarantine') && line.match?(/\bsince=/) }
        return nil unless annotation

        Date.iso8601(annotation[/\bsince=([0-9-]+)/, 1])
      rescue ArgumentError, SystemCallError
        nil
      end
    end
  end
end
