# frozen_string_literal: true

require 'date'

module Necropsy
  module Confidence
    class Scorer
      RUBY_HOOKS = %w[
        inherited included extended prepended method_added singleton_method_added
        const_missing method_missing respond_to_missing?
      ].freeze
      RUBY_PROTOCOLS = %w[
        == eql? hash <=> to_s to_str to_a to_h to_proc inspect each call coerce
        succ initialize_copy marshal_dump marshal_load
      ].freeze
      BUILTIN_IMPLICIT_CALLERS = [
        {
          name_pattern: /^on_/,
          owner_ancestors: ['RuboCop::Cop::Base'],
          reason: 'RuboCop Commissioner dispatches on_* callbacks'
        }
      ].freeze

      def initialize(graph:, reachability:, project:)
        @graph = graph
        @reachability = reachability
        @project = project
        @source_lines = {}
      end

      def findings
        graph.method_nodes.filter_map do |node|
          next if node.test

          classification = classification_for(node)
          next unless classification

          score, level, reasons, score_components = score_for(node, classification)
          Finding.new(
            node: node,
            classification: classification,
            confidence: level,
            score: score,
            score_components: score_components,
            reasons: reasons,
            evidences: graph.incoming_edges(node.id).flat_map(&:evidences) + graph.alive_evidences(node.id)
          )
        end
      end

      private

      attr_reader :graph, :reachability, :project

      def classification_for(node)
        return nil if graph.dynamic_alive?(node.id)

        if reachability.runtime_paths.key?(node.id)
          return :unused if graph.dynamic_enabled? && !generated_accessor?(node)

          nil
        elsif reachability.test_paths.key?(node.id)
          :test_only_reachable
        else
          :unreachable
        end
      end

      def score_for(node, classification)
        reasons = []
        score = base_score(classification)
        components = [score_component("base(#{classification})", score, 'Base classification score')]

        if graph.uncertainties(node.id).any?
          score -= 0.35
          components << score_component('near_metaprogramming', -0.35, 'Unresolved metaprogramming nearby')
          reasons << 'Lowered because this node is near unresolved metaprogramming.'
        end

        if graph.class_info(node.owner)&.dynamic
          score -= 0.25
          components << score_component('dynamic_owner', -0.25, 'Owner defines dynamic dispatch')
          reasons << 'Lowered because the owner class defines dynamic dispatch.'
        end

        if generated_accessor?(node)
          score -= 0.2
          components << score_component('generated_accessor', -0.2, 'Generated by an accessor DSL')
          reasons << 'Lowered because this node is generated by a Ruby accessor DSL.'
        end

        if (reason = implicit_call_context(node))
          score -= 0.4
          components << score_component('implicit_caller', -0.4, reason)
          reasons << "Lowered because #{reason}."
        end

        if classification == :unreachable && graph.dynamic_enabled? && !graph.dynamic_alive?(node.id)
          score += 0.25
          components << score_component('absent_from_dynamic', 0.25, 'Absent from dynamic observations')
          reasons << 'Static unreachable and absent from dynamic observations.'
        end

        if classification == :unreachable && quarantine_expired?(node)
          raised_score = [score, 0.95].max
          components << score_component('expired_quarantine', raised_score - score, 'Expired without alive evidence')
          score = raised_score
          reasons << 'Raised because quarantine annotation has expired without alive evidence.'
        end

        if classification == :unused
          days = observation_days
          if days && days < project.config.min_observation_days
            score -= 0.3
            components << score_component('short_observation', -0.3, "Observed for only #{days} days")
            reasons << "Observation window is #{days} days, below the configured minimum."
          else
            reasons << 'Reachable statically but never observed dynamically.'
          end
        end

        clamped_score = score.clamp(0.0, 1.0)
        components << score_component('score_clamp', clamped_score - score, 'Clamped to the 0.0–1.0 range') if clamped_score != score
        [clamped_score, level_for(clamped_score), reasons, components]
      end

      def score_component(name, value, details)
        ScoreComponent.new(name: name, value: value.round(4), details: details)
      end

      def base_score(classification)
        case classification
        when :unreachable
          0.62
        when :test_only_reachable
          0.55
        when :unused
          0.58
        else
          0.25
        end
      end

      def generated_accessor?(node)
        %i[attr_reader attr_writer attr_accessor struct_new data_define].include?(node.defined_via)
      end

      def implicit_call_reason(node)
        return "#{node.name} is a Ruby hook invoked by the VM" if RUBY_HOOKS.include?(node.name)
        return "#{node.name} is a Ruby protocol method invoked implicitly" if RUBY_PROTOCOLS.include?(node.name)

        rule = implicit_caller_rules.find do |candidate|
          candidate[:name_pattern].match?(node.name) && owner_matches?(node.owner, candidate[:owner_ancestors])
        end
        return unless rule

        rule[:reason] || 'the method matches a configured implicit caller'
      end

      def implicit_call_context(node)
        direct_reason = implicit_call_reason(node)
        return direct_reason if direct_reason

        root_id = implicit_paths[node.id]
        "it is reachable from implicitly invoked #{root_id}" if root_id
      end

      def implicit_paths
        @implicit_paths ||= begin
          roots = graph.method_nodes.reject(&:test).select { |node| implicit_call_reason(node) }.map(&:id)
          paths = roots.to_h { |node_id| [node_id, node_id] }
          queue = roots.dup

          until queue.empty?
            node_id = queue.shift
            graph.edges_from(node_id).each_key do |callee_id|
              next if paths.key?(callee_id)

              paths[callee_id] = paths.fetch(node_id)
              queue << callee_id
            end
          end
          paths
        end
      end

      def implicit_caller_rules
        BUILTIN_IMPLICIT_CALLERS + project.config.implicit_callers
      end

      def owner_matches?(owner, ancestors)
        return true if ancestors.empty?
        return false unless owner

        ancestors.any? { |ancestor| graph.owner_reachable_from_ancestor?(owner, ancestor) }
      end

      def level_for(score)
        return :certain if score >= 0.9
        return :high if score >= 0.7
        return :medium if score >= 0.45

        :low
      end

      def observation_days
        graph.observation.values.filter_map do |value|
          next unless value.is_a?(Hash)

          value['days'] || value[:days] || value['observation_days'] || value[:observation_days]
        end.map(&:to_i).max
      end

      def quarantine_expired?(node)
        since = quarantine_since(node)
        return false unless since

        since <= Date.today - project.config.quarantine_days
      end

      def quarantine_since(node)
        path = File.join(project.root, node.file)
        return nil unless File.exist?(path)

        lines = @source_lines[path] ||= File.readlines(path, chomp: true)
        window = lines[[node.line - 4, 0].max, 4] || []
        annotation = window.find { |line| line.include?('necropsy:quarantine') && line.match?(/\bsince=/) }
        return nil unless annotation

        Date.iso8601(annotation[/\bsince=([0-9-]+)/, 1])
      rescue ArgumentError, SystemCallError
        nil
      end
    end
  end
end
